function [est_depth_vid] = est_depth_video_wrapper(ppvid, mnFrameID, mxFrameID, depth_est_params)


%ppvid = preprocess_wrapper('internal', 'approaching_toward.avi', struct('depth_method', 'fayao', 'opflow_method', 'CLGTV', 'sample_interval', 1, 'scale_to_resolution', [240 320]));

% vidname = 'basketball1'
% interval = 1;
    % ppvid = preprocess_wrapper('princeton', vidname, struct('depth_method', ...
    %                                                   'eigen', ...
    %                                                   'opflow_method', ...
    %                                                   'CLGTV', ...
    %                                                   'sample_interval', ...
    %                                                   interval, ...
    %                                                   'scale_to_resolution', ...
    %                                                   [240 320]));
% mnFrameID = 1;
% mxFrameID = -1; % -1 means last frame



est_depth_vid = est_depth_video(ppvid, mnFrameID, mxFrameID, depth_est_params);
